name: Backend Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and test with Maven
      run: mvn clean verify
      
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage-reports
        path: back/target/site/jacoco/
        retention-days: 7

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: 'back/target/surefire-reports/TEST-*.xml'
        detailed_summary: true
        fail_on_failure: true
