name: Backend Tests & Coverage

on:
  push:
    branches: [ main ]
    paths:
      - 'back/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'back/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run Tests & Generate Coverage Report
      run: mvn verify
      
    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: back/target/site/jacoco/
        retention-days: 7
