name: Docker Publish Frontend

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'front/**'
      - '.github/workflows/docker-publish-frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'front/**'
      - '.github/workflows/docker-publish-frontend.yml'
  workflow_dispatch:

env:
  REGISTRY: docker.io
  FRONTEND_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-frontend

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
