name: SonarCloud Backend Analysis

on:
  push:
    branches: [ main ]
    paths:
      - 'back/**'
      - '.github/workflows/sonarcloud-backend.yml'

permissions:
  pull-requests: read

jobs:
  analyze-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-backend
          restore-keys: ${{ runner.os }}-sonar-backend

      - name: Build and test backend
        run: |
          cd back
          mvn clean verify dependency:copy-dependencies -Pcoverage
          echo "Backend test reports:"
          ls -la target/site/jacoco/
          cat target/site/jacoco/jacoco.xml || echo "No jacoco.xml file found!"

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: back
          args: >
            -Dsonar.projectKey=bobapp-backend
            -Dsonar.organization=jbpoujol
            -Dsonar.java.binaries=target/classes
            -Dsonar.java.test.binaries=target/test-classes
            -Dsonar.java.libraries=target/dependency/*.jar
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
