name: SonarCloud Frontend Analysis

on:
  push:
    branches: [ main ]
    paths:
      - 'front/**'
      - '.github/workflows/sonarcloud-frontend.yml'

permissions:
  pull-requests: read

jobs:
  analyze-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-frontend
          restore-keys: ${{ runner.os }}-sonar-frontend

      - name: Install frontend dependencies
        run: |
          cd front
          npm ci
          npm install -D karma-junit-reporter

      - name: Build and test frontend
        env:
          CHROME_BIN: /usr/bin/chromium-browser
        run: |
          cd front
          npm run test -- --no-watch --code-coverage --browsers=ChromeHeadless
          echo "Frontend test reports:"
          ls -la coverage/bobapp/
          cat coverage/bobapp/lcov.info || echo "No lcov.info file found!"

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=bobapp-frontend
            -Dsonar.organization=jbpoujol
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
